language: java
os: linux

script: xvfb-run 

addons:
  sonarcloud:
    organization: "0088t00127087-github" # the key of the org you chose at step #3
    token:
      secure: "5fad22f3ac092d0c7267e2bf61a3623fb8167097" # encrypted value of your token
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
